using Cinemachine;
using StarterAssets;
using System.Collections.Generic;
using TMPro;
using UnityEngine;

public class ActiveWeapon : MonoBehaviour
{
    [SerializeField] WeaponSO starterWeapon;
    [SerializeField] CinemachineVirtualCamera playerCamera;
    [SerializeField] GameObject zoomOverlay;
    [SerializeField] TMP_Text ammoText;

    WeaponSO currentWeaponSO;

    Animator animator;
    StarterAssetsInputs starterAssetsInputs;
    FirstPersonController firstPersonController;
    Weapon activeWeapon;

    const string SHOOT_STRING = "Shoot";

    float timeSinceLastShot = 0f;
    float defaultFOV;
    float defaultRotationSpeed;

    int currentMag;
    Dictionary<WeaponSO, int> magAmmo = new();
    Dictionary<WeaponSO, int> reserveAmmo = new();

    void Awake()
    {
        starterAssetsInputs = GetComponentInParent<StarterAssetsInputs>();
        firstPersonController = GetComponentInParent<FirstPersonController>();
        animator = GetComponent<Animator>();
        defaultFOV = playerCamera.m_Lens.FieldOfView;
        defaultRotationSpeed = firstPersonController.RotationSpeed;
    }

    void Start()
    {
        SwitchWeapon(starterWeapon);
    }

    void Update()
    {
        PlayerShoot();
        PlayerZoom();
        PlayerReload();
    }

    public void AdjustAmmo(int magazines)
    {
        currentMag = currentWeaponSO.MagazineSize;
        magAmmo[currentWeaponSO] = currentMag;

        int current = reserveAmmo[currentWeaponSO];
        reserveAmmo[currentWeaponSO] = Mathf.Clamp(current + magazines, 0, currentWeaponSO.MaxReserveMagazines);
        UpdateAmmoText();
    }

    public void SwitchWeapon(WeaponSO weaponSO)
    {
        if (currentWeaponSO != null)
            magAmmo[currentWeaponSO] = currentMag;

        if (activeWeapon)
            Destroy(activeWeapon.gameObject);

        Weapon newWeapon = Instantiate(weaponSO.WeaponPrefab, transform).GetComponent<Weapon>();
        activeWeapon = newWeapon;
        currentWeaponSO = weaponSO;
        timeSinceLastShot = 0f;

        if (!magAmmo.ContainsKey(weaponSO))
        {
            magAmmo[weaponSO] = weaponSO.MagazineSize;
            reserveAmmo[weaponSO] = weaponSO.MaxReserveMagazines;
        }

        currentMag = magAmmo[weaponSO];
        UpdateAmmoText();
    }

    void PlayerShoot()
    {
        timeSinceLastShot += Time.deltaTime;

        if (!starterAssetsInputs.shoot) return;
        if (currentMag <= 0) return;
        if (timeSinceLastShot < currentWeaponSO.FireRate) return;

        activeWeapon.PlayerShoot(currentWeaponSO);
        animator.Play(SHOOT_STRING, 0, 0f);
        timeSinceLastShot = 0f;

        currentMag--;
        magAmmo[currentWeaponSO] = currentMag;
        UpdateAmmoText();

        if (!currentWeaponSO.IsAutomatic)
            starterAssetsInputs.ShootInput(false);
    }

    // this function was generated by Claude, 
    // and is used to handle the player's reload input and logic
    void PlayerReload()
    {
        if (!starterAssetsInputs.reload) return;
        starterAssetsInputs.ReloadInput(false);

        if (currentMag == currentWeaponSO.MagazineSize) return;

        int reserve = reserveAmmo[currentWeaponSO];
        if (reserve <= 0) return;

        currentMag = currentWeaponSO.MagazineSize;
        reserveAmmo[currentWeaponSO] = reserve - 1;
        magAmmo[currentWeaponSO] = currentMag;
        UpdateAmmoText();
    }

    void PlayerZoom()
    {
        if (!currentWeaponSO.CanZoom) return;

        if (starterAssetsInputs.zoom)
        {
            playerCamera.m_Lens.FieldOfView = currentWeaponSO.ZoomFOV;
            zoomOverlay.SetActive(true);
            firstPersonController.ChangeRotationSpeed(currentWeaponSO.ZoomRotationSpeed);
        }
        else
        {
            playerCamera.m_Lens.FieldOfView = defaultFOV;
            zoomOverlay.SetActive(false);
            firstPersonController.ChangeRotationSpeed(defaultRotationSpeed);
        }
    }

    void UpdateAmmoText()
    {
        int reserve = reserveAmmo[currentWeaponSO];
        ammoText.text = $"{currentMag:D2} | {reserve:D2}";
    }
}
